Repository Rishit-dagli/People-Counter-On-Edge, pull requests merged in 2020-05, with the labels that each got.

#2 Create python_syntax.yml
  .github/workflows/python_syntax.yml
Labels: size/XS

#3 Create stale.yml
  .github/workflows/stale.yml
Labels: size/S

#4 Please correct it. I hope its what you wanted ;)
  WRITEUP.md
Labels: cla: yes, size/XS
